const fs = require("fs");
const path = require("path");
const Module = require("module");

const targetPath = path.join(__dirname, "..", "index.js");
let source = fs.readFileSync(targetPath, "utf8").replace(/^\uFEFF/, "");

function replaceOnce(pattern, replacement, label) {
  if (!pattern.test(source)) {
    throw new Error(`Nao consegui aplicar o patch de runtime: ${label}`);
  }
  source = source.replace(pattern, replacement);
}

replaceOnce(
  /const \{\r?\n  DISCORD_TOKEN,\r?\n  TICKET_PANEL_CHANNEL_ID,\r?\n/,
  [
    "const {",
    "  DISCORD_TOKEN,",
    "  TICKET_PANEL_CHANNEL_ID,",
    "  SUPPORT_PANEL_CHANNEL_ID,",
    "  ENCOMENDA_PANEL_CHANNEL_ID,",
    ""
  ].join("\n"),
  "env vars"
);

replaceOnce(
  /const STORAGE_PATH = path\.join\(__dirname, "storage\.json"\);\r?\nfunction readStorage\(\) \{[\s\S]*?function nextTicketNumber\(\) \{[\s\S]*?return s\.ticketCounter;\r?\n\}/,
  [
    "const STORAGE_PATH = path.join(__dirname, \"storage.json\");",
    "const STORAGE_DEFAULTS = {",
    "  panelMessageId: null,",
    "  panelMessageIds: {},",
    "  ticketCounter: 0,",
    "  c4Daily: {},",
    "  recruitAttempts: {}",
    "};",
    "",
    "function normalizeStorage(data) {",
    "  const next = {",
    "    ...STORAGE_DEFAULTS,",
    "    ...(data && typeof data === \"object\" ? data : {})",
    "  };",
    "",
    "  if (!next.panelMessageIds || typeof next.panelMessageIds !== \"object\" || Array.isArray(next.panelMessageIds)) {",
    "    next.panelMessageIds = {};",
    "  }",
    "",
    "  if (next.panelMessageId && !next.panelMessageIds.combined) {",
    "    next.panelMessageIds.combined = next.panelMessageId;",
    "  }",
    "",
    "  return next;",
    "}",
    "",
    "function readStorage() {",
    "  try {",
    "    return normalizeStorage(JSON.parse(fs.readFileSync(STORAGE_PATH, \"utf8\")));",
    "  } catch {",
    "    return normalizeStorage();",
    "  }",
    "}",
    "function writeStorage(data) {",
    "  fs.writeFileSync(STORAGE_PATH, JSON.stringify(normalizeStorage(data), null, 2), \"utf8\");",
    "}",
    "function nextTicketNumber() {",
    "  const s = readStorage();",
    "  s.ticketCounter = (s.ticketCounter || 0) + 1;",
    "  writeStorage(s);",
    "  return s.ticketCounter;",
    "}"
  ].join("\n"),
  "storage"
);

replaceOnce(
  /function makePanelEmbed\(\) \{[\s\S]*?\r?\n\}\r?\n\r?\nfunction makePanelButtons\(\) \{[\s\S]*?\r?\n\}\r?\n\r?\nfunction sanitizeChannelName/,
  [
    "function makeTicketRulesField() {",
    "  return {",
    "    name: \"\\u{1F4CB} Regras R\\u00E1pidas\",",
    "    value: [",
    "      \"Um ticket por assunto.\",",
    "      \"Mantenha respeito e objetividade.\",",
    "      \"Responda dentro do prazo informado.\"",
    "    ].join(\"\\n\"),",
    "    inline: false",
    "  };",
    "}",
    "",
    "function makeCombinedPanelEmbed() {",
    "  return new EmbedBuilder()",
    "    .setColor(0xE11D2E)",
    "    .setTitle(\"\\u{1F1E8}\\u{1F1ED} Central de Atendimento | Su\\u00ED\\u00E7a\")",
    "    .setDescription(\"Selecione abaixo a categoria correta para abrir um ticket privado com a equipe.\")",
    "    .addFields(",
    "      {",
    "        name: \"\\u2753 D\\u00FAvidas\",",
    "        value: \"Suporte geral, orienta\\u00E7\\u00F5es e ajuda com procedimentos.\",",
    "        inline: true",
    "      },",
    "      {",
    "        name: \"\\u{1F4E6} Encomendas\",",
    "        value: \"Pedidos, servi\\u00E7os e acompanhamento do atendimento.\",",
    "        inline: true",
    "      },",
    "      {",
    "        name: \"\\u{1F4DD} Recrutamento\",",
    "        value: \"Sele\\u00E7\\u00E3o RP. Dispon\\u00EDvel de segunda a sexta.\",",
    "        inline: true",
    "      },",
    "      {",
    "        name: \"\\u{1F6A8} Den\\u00FAncias\",",
    "        value: \"Envie provas em v\\u00EDdeo do YouTube e detalhes do caso.\",",
    "        inline: true",
    "      },",
    "      makeTicketRulesField()",
    "    )",
    "    .setFooter({ text: \"Su\\u00ED\\u00E7a | Atendimento autom\\u00E1tico\" });",
    "}",
    "",
    "function makeCombinedPanelButtons() {",
    "  return new ActionRowBuilder().addComponents(",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_duvidas\")",
    "      .setLabel(\"D\\u00FAvidas\")",
    "      .setStyle(ButtonStyle.Primary)",
    "      .setEmoji({ name: \"\\u2753\" }),",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_encomenda\")",
    "      .setLabel(\"Encomenda\")",
    "      .setStyle(ButtonStyle.Secondary)",
    "      .setEmoji({ name: \"\\u{1F4E6}\" }),",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_recrutamento\")",
    "      .setLabel(\"Recrutamento\")",
    "      .setStyle(ButtonStyle.Success)",
    "      .setEmoji({ name: \"\\u{1F4DD}\" }),",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_denuncia\")",
    "      .setLabel(\"Den\\u00FAncias\")",
    "      .setStyle(ButtonStyle.Danger)",
    "      .setEmoji({ name: \"\\u{1F6A8}\" })",
    "  );",
    "}",
    "",
    "function makeSupportPanelEmbed() {",
    "  return new EmbedBuilder()",
    "    .setColor(0xE11D2E)",
    "    .setTitle(\"\\u{1F1E8}\\u{1F1ED} Central de Suporte | Su\\u00ED\\u00E7a\")",
    "    .setDescription(\"Abra aqui tickets de recrutamento, d\\u00FAvidas e den\\u00FAncias.\")",
    "    .addFields(",
    "      {",
    "        name: \"\\u{1F4DD} Recrutamento\",",
    "        value: \"Sele\\u00E7\\u00E3o RP. Dispon\\u00EDvel de segunda a sexta.\",",
    "        inline: true",
    "      },",
    "      {",
    "        name: \"\\u2753 D\\u00FAvidas\",",
    "        value: \"Suporte geral, orienta\\u00E7\\u00F5es e ajuda com procedimentos.\",",
    "        inline: true",
    "      },",
    "      {",
    "        name: \"\\u{1F6A8} Den\\u00FAncias\",",
    "        value: \"Envie provas em v\\u00EDdeo do YouTube e detalhes do caso.\",",
    "        inline: true",
    "      },",
    "      makeTicketRulesField()",
    "    )",
    "    .setFooter({ text: \"Su\\u00ED\\u00E7a | Suporte autom\\u00E1tico\" });",
    "}",
    "",
    "function makeSupportPanelButtons() {",
    "  return new ActionRowBuilder().addComponents(",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_recrutamento\")",
    "      .setLabel(\"Recrutamento\")",
    "      .setStyle(ButtonStyle.Success)",
    "      .setEmoji({ name: \"\\u{1F4DD}\" }),",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_duvidas\")",
    "      .setLabel(\"D\\u00FAvidas\")",
    "      .setStyle(ButtonStyle.Primary)",
    "      .setEmoji({ name: \"\\u2753\" }),",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_denuncia\")",
    "      .setLabel(\"Den\\u00FAncias\")",
    "      .setStyle(ButtonStyle.Danger)",
    "      .setEmoji({ name: \"\\u{1F6A8}\" })",
    "  );",
    "}",
    "",
    "function makeOrderPanelEmbed() {",
    "  return new EmbedBuilder()",
    "    .setColor(0x2563EB)",
    "    .setTitle(\"\\u{1F4E6} Central de Encomendas | Su\\u00ED\\u00E7a\")",
    "    .setDescription(\"Abra aqui seu ticket de encomenda para montar e acompanhar o pedido com a equipe.\")",
    "    .addFields(",
    "      {",
    "        name: \"\\u{1F4E6} Encomenda\",",
    "        value: \"Pedidos, servi\\u00E7os e acompanhamento do atendimento.\",",
    "        inline: false",
    "      },",
    "      makeTicketRulesField()",
    "    )",
    "    .setFooter({ text: \"Su\\u00ED\\u00E7a | Encomendas autom\\u00E1ticas\" });",
    "}",
    "",
    "function makeOrderPanelButtons() {",
    "  return new ActionRowBuilder().addComponents(",
    "    new ButtonBuilder()",
    "      .setCustomId(\"ticket_encomenda\")",
    "      .setLabel(\"Encomenda\")",
    "      .setStyle(ButtonStyle.Secondary)",
    "      .setEmoji({ name: \"\\u{1F4E6}\" })",
    "  );",
    "}",
    "",
    "function sanitizeChannelName"
  ].join("\n"),
  "painel"
);

replaceOnce(
  /async function ensurePanel\(interactionOrGuild\) \{[\s\S]*?\r?\n\}\r?\n\r?\nclient\.on\("clientReady"/,
  [
    "function getPanelConfigs() {",
    "  const supportPanelId = String(SUPPORT_PANEL_CHANNEL_ID || \"\").trim();",
    "  const orderPanelId = String(ENCOMENDA_PANEL_CHANNEL_ID || \"\").trim();",
    "  const legacyPanelId = String(TICKET_PANEL_CHANNEL_ID || \"\").trim();",
    "",
    "  if (!supportPanelId && !orderPanelId) {",
    "    if (!legacyPanelId) return [];",
    "    return [",
    "      {",
    "        key: \"combined\",",
    "        label: \"atendimento\",",
    "        channelId: legacyPanelId,",
    "        payload: { embeds: [makeCombinedPanelEmbed()], components: [makeCombinedPanelButtons()] }",
    "      }",
    "    ];",
    "  }",
    "",
    "  return [",
    "    {",
    "      key: \"support\",",
    "      label: \"suporte\",",
    "      channelId: supportPanelId || legacyPanelId,",
    "      payload: { embeds: [makeSupportPanelEmbed()], components: [makeSupportPanelButtons()] }",
    "    },",
    "    {",
    "      key: \"order\",",
    "      label: \"encomenda\",",
    "      channelId: orderPanelId || legacyPanelId,",
    "      payload: { embeds: [makeOrderPanelEmbed()], components: [makeOrderPanelButtons()] }",
    "    }",
    "  ].filter((panel) => panel.channelId);",
    "}",
    "",
    "async function upsertPanelMessage(channel, messageId, payload) {",
    "  if (messageId) {",
    "    const msg = await channel.messages.fetch(messageId).catch(() => null);",
    "    if (msg) {",
    "      await msg.edit(payload).catch(() => {});",
    "      return msg;",
    "    }",
    "  }",
    "",
    "  return channel.send(payload);",
    "}",
    "",
    "async function ensurePanel(interactionOrGuild) {",
    "  const guild = interactionOrGuild.guild ?? interactionOrGuild;",
    "  const storage = readStorage();",
    "  const panelConfigs = getPanelConfigs();",
    "",
    "  if (!panelConfigs.length) {",
    "    return {",
    "      ok: false,",
    "      reason: \"Configure TICKET_PANEL_CHANNEL_ID ou SUPPORT_PANEL_CHANNEL_ID/ENCOMENDA_PANEL_CHANNEL_ID.\"",
    "    };",
    "  }",
    "",
    "  const resolvedPanels = [];",
    "  for (const panel of panelConfigs) {",
    "    const channel = await guild.channels.fetch(panel.channelId).catch(() => null);",
    "    if (!channel) {",
    "      return { ok: false, reason: `Canal do painel de ${panel.label} nao encontrado.` };",
    "    }",
    "    resolvedPanels.push({ ...panel, channel });",
    "  }",
    "",
    "  storage.panelMessageIds = storage.panelMessageIds || {};",
    "",
    "  const results = [];",
    "  for (const panel of resolvedPanels) {",
    "    const legacyMessageId = panel.key === \"combined\" ? storage.panelMessageId : null;",
    "    const messageId = storage.panelMessageIds[panel.key] || legacyMessageId;",
    "    const msg = await upsertPanelMessage(panel.channel, messageId, panel.payload);",
    "",
    "    storage.panelMessageIds[panel.key] = msg.id;",
    "    if (panel.key === \"combined\") {",
    "      storage.panelMessageId = msg.id;",
    "    }",
    "",
    "    results.push({",
    "      key: panel.key,",
    "      label: panel.label,",
    "      channelId: panel.channel.id,",
    "      messageId: msg.id",
    "    });",
    "  }",
    "",
    "  const summary = results.map((panel) => `${panel.label}: ${panel.messageId}`).join(\" | \"");",
    "  writeStorage(storage);",
    "  return { ok: true, panels: results, messageId: summary || null };",
    "}",
    "",
    "client.on(\"clientReady\""
  ].join("\n"),
  "ensurePanel"
);

const runtimeModule = new Module(targetPath, module);
runtimeModule.filename = targetPath;
runtimeModule.paths = Module._nodeModulePaths(path.dirname(targetPath));
runtimeModule._compile(source, targetPath);
